# Cache config
cache:
    enabled: true # default: false
    max_body_size: 1048576 # in bytes
    capacity: 100 # number of response entries for GET and HEAD, default: 100, should be > 0
    type: "LRU" # "LRU" , "LFU" is a future implementation
    ttl: 300 # in seconds, should be > 0, absolute TTL for each cache entry

# Services config
services:
    - name: "svc1"
      listen_port: 80
      balancer: "RoundRobin"

      hosts:
          - "http://localhost/"
          - "http://127.0.0.1"

      upstreams:
          - host: "http://localhost:6000"
            health_uri: "/health"
          - host: "http://localhost:7000"
            health_uri: "/"

    - name: "svc2"
      listen_port: 5000
      balancer: "RoundRobin"

      hosts:
          - "http://localhost/"
          - "http://127.0.0.1"

      upstreams:
          - host: "http://localhost:8000"
            health_uri: "/health"
          - host: "http://localhost:6000"
            health_uri: "/"
