services:
    - name: "svc1"
      listen_port: 80
      balancer: "RoundRobin"

      hosts:
          - "http://localhost:80/"
          - "http://127.0.0.1:80"

      upstreams:
          - host: "http://localhost:8000"
            health_uri: "/health" # should start with /
          - host: "http://localhost:9000"
            health_uri: "/" # default value

    - name: "svc2"
      listen_port: 5000
      balancer: "RoundRobin"

      hosts:
          - "http://localhost:5000/"
          - "http://127.0.0.1:5000"

      upstreams:
          - host: "http://localhost:6000"
            health_uri: "/health" # should start with /
          - host: "http://localhost:7000"
            health_uri: "/" # default value
